flags: {}
extra-package-dbs: []
packages:
- location: '.'
- extra-dep: true
  location:
    git: 'https://github.com/filopodia/open.git'
    commit: '387683d052c370cd010827048fc75649e9590447'
  subdirs:
    - inliterate
    - plotlyhs
    - lucid-extras
- '.'
- location:
    git: https://github.com/tensorflow/haskell.git
    commit: 4ab9cb9cf274e88eababfaba85103e3890a96afc
  subdirs:
  - tensorflow
  - tensorflow-ops
  - tensorflow-core-ops
  - tensorflow-logging
  - tensorflow-proto
  - tensorflow-opgen
  - tensorflow-test
  - tensorflow-mnist
  - tensorflow-mnist-input-data
  extra-dep: true
extra-deps:
- proto-lens-protobuf-types-0.2.1.0
- snappy-0.2.0.2
- snappy-framing-0.1.1
- tensorflow-logging-0.1.0.0
- tensorflow-records-0.1.0.0
- tensorflow-records-conduit-0.1.0.0
extra-include-dirs:
- /usr/local/opt/icu4c/include
extra-lib-dirs:
- /usr/local/opt/icu4c/lib
resolver: lts-8.20
