resolver: lts-11.9
flags: {}
extra-package-dbs: []
packages:
- location: '.'
- extra-dep: true
  location:
    git: 'https://github.com/filopodia/open.git'
    commit: '387683d052c370cd010827048fc75649e9590447'
  subdirs:
    - inliterate
    - plotlyhs
    - lucid-extras
- location:
    git: https://github.com/tensorflow/haskell.git
    commit: 8e1d85b5e5bd56d54ff6d463c8581c57ab5526d9
  subdirs:
  - tensorflow
  - tensorflow-ops
  - tensorflow-core-ops
  - tensorflow-proto
  - tensorflow-opgen
  - tensorflow-test
  - tensorflow-mnist
  - tensorflow-mnist-input-data
  extra-dep: true
extra-deps:
- proto-lens-protobuf-types-0.2.2.0
- proto-lens-0.2.2.0
- proto-lens-protoc-0.2.2.3
- snappy-0.2.0.2
- snappy-framing-0.1.1
- haskell-src-exts-1.19.1
extra-include-dirs:
- /usr/local/opt/icu4c/include
extra-lib-dirs:
- /usr/local/opt/icu4c/lib
