resolver: lts-11.9
flags: {}
extra-package-dbs: []
packages:
- location: '.'
- extra-dep: true
  location:
    git: https://github.com/filopodia/open.git
    commit: 387683d052c370cd010827048fc75649e9590447
  subdirs:
    - inliterate
    - plotlyhs
    - lucid-extras
- location:
    git: https://github.com/tensorflow/haskell.git
    commit: 99f8c8cf5658750
  subdirs:
  - tensorflow
  - tensorflow-ops
  - tensorflow-core-ops
  - tensorflow-proto
  - tensorflow-opgen
  - tensorflow-test
  - tensorflow-mnist
  - tensorflow-mnist-input-data
  extra-dep: true
extra-deps:
- snappy-framing-0.1.1
- snappy-0.2.0.2
# `haskell-src-exts < 1.20` is needed due the dependency on
# `proto-lens-protoc < 0.3` in the `tensorflow-proto` package:
- haskell-src-exts-1.19.1
- proto-lens-protobuf-types-0.2.2.0
- proto-lens-protoc-0.2.2.3

extra-include-dirs:
- /usr/local/opt/icu4c/include
- /usr/local/include
extra-lib-dirs:
- /usr/local/opt/icu4c/lib
- /usr/local/lib

nix:
    enable: false
    shell-file: shell.nix

